name: Test (push)

on:
  push:
    branches:
      - "!v*"
      - "**"

env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    name: Full Test Suite (All tiers)
    runs-on: ubuntu-latest
    needs:
      - tests_t1
      - tests_t2
    steps:
      - name: Finish full test suite
        run: exit 0
  tests_t1:
    name: Tier 1 Tests
    runs-on: ubuntu-latest
    needs:
      - test_64bit
      - test_32bit
    steps:
      - name: Finish Tier 1 Tests
        run: exit 0
  tests_t2:
    name: Tier 2 Tests
    runs-on: ubuntu-latest
    needs:
      - test_tier2
    steps:
      - name: Finish Tier 2 Tests
        run: exit 0
  test_64bit:
    name: Test (Tier 1) (64-bit) ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust: x86_64-apple-darwin
          - os: windows-latest
            rust: x86_64-pc-windows-msvc
          - os: [self-hosted, ARM64]
            rust: aarch64-unknown-linux-gnu
          - os: macos-14
            rust: aarch64-apple-darwin

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install GNU tar
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
        if: runner.os == 'macOS'
      - name: Setup environment
        run: |
          chmod +x ci/setvars.sh
          ci/setvars.sh

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ matrix.rust }}-cargocache-${{ hashFiles('Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust }}

      - name: Run Tests
        run: make test
        env:
          RUST_BACKTRACE: 1
          TARGET: ${{ matrix.rust }}

  test_32bit:
    name: Test (Tier 1) (32-bit) ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: i686-unknown-linux-gnu
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup environment
        run: |
          chmod +x ci/setvars.sh
          ci/setvars.sh

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ matrix.rust }}-cargocache-${{ hashFiles('Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust }}

      - name: Run Tests
        run: make test
        env:
          RUST_BACKTRACE: 1
          TARGET: ${{ matrix.rust }}

  test_tier2:
    name: Test (Tier 2) ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust: x86_64-unknown-linux-musl
          - os: windows-latest
            rust: i686-pc-windows-msvc
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup environment
        run: |
          chmod +x ci/setvars.sh
          ci/setvars.sh

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./target
          key: ${{ matrix.rust }}-cargocache-${{ hashFiles('Cargo.lock') }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.rust }}

      - name: Run Tests
        run: make test
        env:
          RUST_BACKTRACE: 1
          TARGET: ${{ matrix.rust }}
